# Generated by Django 3.1 on 2021-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200123_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='There are no description provided for this book! ', verbose_name='Text summary of the book'),
        ),
    ]
