# Generated by Django 3.1 on 2021-05-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20210516_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='There are no description provided for this book! ', verbose_name='Text summary of the book'),
        ),
    ]
